from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.modules.users.domain.entities import User
from app.modules.users.domain.enums import UserRole, UserStatus


class UserRepository(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...

    async def get_by_id(self, user_id: UUID) -> User | None: ...

    async def get_or_create(self, email: str, now: datetime) -> User: ...

    async def set_verified(self, user_id: UUID, value: bool) -> None: ...

    async def count_users(self, *, role: UserRole | None = None) -> int: ...

    async def list_users(self, *, offset: int, limit: int, role: UserRole | None = None) -> list[User]: ...

    async def update_role(self, user_id: UUID, role: UserRole) -> User | None: ...

    async def update_status(self, user_id: UUID, status: UserStatus) -> User | None: ...
